apiVersion: v1
kind: Pod
metadata:
  name: nginx
  Namespace: roboshop
  lables:
    environment: dev
    project: roboshop
spec:
  containers:
    name: nginx
    image: nginx
    ports:
      ContainerPort: 80

